### ISSUE TITLE
Can't delete a slice: "Invalid value for `graph_id`, must not be `None`"

### ISSUE THREAD

**Issue by sajith** [fabric-testbed/fabric-cli#47]
Not sure what this means:

```console
$ fabric-cli slices delete --sliceid 9f95339d-6bbb-4422-9e95-9666c815dd33 
Error: Invalid value for `graph_id`, must not be `None`
```

**Comment by sajith** [comment]
I'm getting the same error message from `fabric-cli slivers query` as well.  Should that be a separate issue?

**Comment by kthare10** [comment]
I am unable to reproduce this.

**Comment by sajith** [comment]
Tried again, and I too am unable to reproduce this today. `fabric-cli slivers query` produces a normal-looking output (not the error originally reported), and `fabric-cli slices delete` is printing some `BAD REQUEST` errors ("details" field in the error message's body suggests that the slices I'm trying to delete are already closed).

I'll close this.
